version: "3.0"

services:
    mongodb:
        image: "mongo:4.2.16"
        ports:
            - "37017:27017"
        command: mongod

    my-app:
        depends_on:
            - mongodb
        # image: "bagusrizkis/demo-app:1.0"
        build: .
        ports:
            - "5005:3000"
        command: "npm run dev"
        volumes:
            - ./:/usr/demoapp/server
            - ./node_modules
        environment:
            MONGO_URL: "mongodb"
        links:
            - mongodb
